# This config contains the default values for training an English 22.05kHz DiscreteSpeech model.
# If you want to train a model on other dataset, you can change config values according to your dataset.
# Most dataset-specific arguments are in the head of the config file, see below.

name: DiscreteSpeech

batch_size: 600

max_epochs: ???

feature_name: ???
audio_codec_path: ???

train_ds_type: ???
train_ds_meta: ???
val_ds_meta: ???
log_ds_meta: ???

phoneme_dict_path: ???
heteronyms_path: ???

log_dir: ???

freeze_aligner: ???

codebook_num: 7
codebook_levels: [4, 4, 4, 4, 4, 4]
codebook_dim: 6
codebook_emb_dim: 42
codebook_size: 4096

acoustic_codebook_num: 6

context_max_len: 250

num_duration: 20
num_speaking_rate: 41

fps_max: -1.2
fps_min: -2.4

feature_readers:
  audio_codec:
    _target_: nemo.collections.tts.parts.preprocessing.features.AudioCodecFeatureReader
    feature_filename: ${feature_name}

train_feature_readers:
  audio_codec:
    _target_: nemo.collections.tts.parts.preprocessing.features.AudioCodecFeatureReader
    feature_name: "audio_tokens"
    feature_len_field: "audio_token_lens"
  context_codec:
    _target_: nemo.collections.tts.parts.preprocessing.features.AudioCodecFeatureReader
    feature_name: "context_tokens"
    feature_len_field: "context_token_lens"

context_emb_dim: 512

context_hidden_dim: 768
context_filters: 3072

text_hidden_dim: 768
text_filters: 3072

duration_hidden_dim: 512
duration_filters: 2048

audio_hidden_dim: 768
audio_filters: 3072

model:
  freeze_aligner: ${freeze_aligner}

  context_max_len: ${context_max_len}
  max_token_duration: ${num_duration}

  semantic_codebook_num: 1
  acoustic_codebook_num: ${acoustic_codebook_num}

  vector_quantizer:
    _target_: nemo.collections.tts.modules.audio_codec_modules.GroupFiniteScalarQuantizer
    num_groups: ${codebook_num}
    num_levels_per_group: ${codebook_levels}

  text_tokenizer:
    _target_: nemo.collections.common.tokenizers.text_to_speech.tts_tokenizers.IPATokenizer
    punct: true
    apostrophe: true
    pad_with_space: false
    skip_oov: false
    add_boundaries: true
    non_default_punct_list: [
      ',', '.', '!', '?', '-',
      ':', ';', '/', '"', '(',
      ')', '[', ']', '{', '}',
      '&', '<', '>', "«", "»",
      "'", '~', '+', '–', '—',
    ]
    g2p:
      _target_: nemo.collections.tts.g2p.models.i18n_ipa.IpaG2p
      phoneme_dict: ${phoneme_dict_path}
      heteronyms: ${heteronyms_path}
      phoneme_probability: 0.9
      use_chars: true
      use_stresses: false

  train_ds:
    dataset:
      dataset_type: ${train_ds_type}
      dataset_args:
        dataset_meta: ${train_ds_meta}
        feature_readers: ${train_feature_readers}
        batch_duration: ${batch_size}
        pc_dropout_rate: 0.1
        min_duration: 1.0
        max_duration: 20.1

    dataloader_params:
      batch_size: 1
      num_workers: 4
      persistent_workers: false

  validation_ds:
    dataset:
      dataset_type: default
      dataset_args:
        dataset_meta: ${val_ds_meta}
        feature_readers: ${feature_readers}
        min_duration: 3.0
        max_duration: 20.1

    dataloader_params:
      batch_size: 8
      num_workers: 1

  log_config:
    log_dir: ${log_dir}
    log_epochs: [1, 10]
    epoch_frequency: 20
    log_tensorboard: false
    log_wandb: false
    max_filename_len: 100

    generators:
      - _target_: nemo.collections.tts.parts.utils.callbacks.DiscreteSpeechArtifactGenerator
        audio_codec_path: ${audio_codec_path}
        log_audio: true
        audio_weight: 4.0
        audio_topk: 40
        audio_temperature: 0.5
        acoustic_topk: 20
        acoustic_temperature: 0.4
        duration_weight: 1.0
        duration_topk: 3
        duration_temperature: 0.7
        silence_pad_start: 1
        silence_pad_end: 2

    dataset:
      dataset_type: default
      dataset_args:
        dataset_meta: ${log_ds_meta}
        feature_readers: ${feature_readers}

    dataloader_params:
      batch_size: 8
      num_workers: 1

  aligner:
    _target_: nemo.collections.tts.modules.discrete_speech_modules.Aligner
    text_emb_dim: 256
    prior_scaling_factor: 0.1
    alignment_encoder:
      _target_: nemo.collections.tts.modules.aligner.AlignmentEncoder
      n_mel_channels: ${codebook_emb_dim}
      n_text_channels: 256
      dist_type: cosine
      temperature: 20.0
      n_att_channels: 128
      n_mel_filters: 256

  context_encoder:
    _target_: nemo.collections.tts.modules.discrete_speech_modules.ContextEncoder
    input_dim: ${codebook_emb_dim}
    output_dim: ${context_emb_dim}
    d_model: ${context_hidden_dim}
    transformer:
      _target_: nemo.collections.tts.modules.transformer_2501.Transformer
      n_layers: 6
      d_model: ${context_hidden_dim}
      d_ffn: ${context_filters}
      sa_n_heads: 8
      kernel_size: 1
      p_dropout: 0.1
      ffn_type: "swiglu"
      use_static_pos_emb: true
      has_xattn: false
      is_causal: false

  text_encoder:
    _target_: nemo.collections.tts.modules.discrete_speech_modules.TextEncoder
    d_model: ${text_hidden_dim}
    d_context: ${context_emb_dim}
    transformer:
      _target_: nemo.collections.tts.modules.transformer_2501.Transformer
      n_layers: 10
      d_model: ${text_hidden_dim}
      d_ffn: ${text_filters}
      sa_n_heads: 8
      kernel_size: 1
      p_dropout: 0.1
      ffn_type: "swiglu"
      use_static_pos_emb: true
      has_xattn: false
      is_causal: false

  decoder:
    _target_: nemo.collections.tts.modules.discrete_speech_modules.AudioDecoder
    input_dim: ${text_hidden_dim}
    d_model: ${audio_hidden_dim}
    num_acoustic_codebooks: ${acoustic_codebook_num}
    codebook_size: ${codebook_size}
    codebook_dim: ${codebook_dim}
    parallel_transformer:
      _target_: nemo.collections.tts.modules.transformer_2501.Transformer
      n_layers: 6
      d_model: ${audio_hidden_dim}
      d_ffn: ${audio_filters}
      sa_n_heads: 8
      kernel_size: 7
      p_dropout: 0.1
      ffn_type: "convnext"
      use_static_pos_emb: true
      has_xattn: false
      is_causal: false
    semantic_transformer:
      _target_: nemo.collections.tts.modules.transformer_2501.Transformer
      n_layers: 6
      d_model: ${audio_hidden_dim}
      d_ffn: ${audio_filters}
      sa_n_heads: 8
      kernel_size: 1
      p_dropout: 0.1
      ffn_type: "swiglu"
      use_static_pos_emb: false
      has_xattn: false
      is_causal: true
    acoustic_transformer_kwargs:
        n_layers: 2
        d_model: ${audio_hidden_dim}
        d_ffn: ${audio_filters}
        sa_n_heads: 8
        kernel_size: 1
        p_dropout: 0.1
        ffn_type: "swiglu"
        use_static_pos_emb: false
        has_xattn: false
        is_causal: true

  duration_decoder:
    _target_: nemo.collections.tts.modules.discrete_speech_modules.DurationDecoder
    input_dim: ${text_hidden_dim}
    d_model: ${duration_hidden_dim}
    num_duration: ${num_duration}
    parallel_transformer:
      _target_: nemo.collections.tts.modules.transformer_2501.Transformer
      n_layers: 8
      d_model: ${duration_hidden_dim}
      d_ffn: ${duration_filters}
      sa_n_heads: 8
      kernel_size: 1
      p_dropout: 0.1
      ffn_type: "swiglu"
      use_static_pos_emb: true
      has_xattn: false
      is_causal: false
    duration_transformer:
      _target_: nemo.collections.tts.modules.transformer_2501.Transformer
      n_layers: 6
      d_model: ${duration_hidden_dim}
      d_ffn: ${duration_filters}
      sa_n_heads: 8
      kernel_size: 1
      p_dropout: 0.1
      ffn_type: "swiglu"
      use_static_pos_emb: true
      has_xattn: false
      is_causal: true

  speaking_rate_predictor:
    _target_: nemo.collections.tts.modules.discrete_speech_modules.SpeakingRatePredictor
    num_speaking_rate: ${num_speaking_rate}
    context_dim: ${context_emb_dim}

  speaking_rate_quantizer:
    _target_: nemo.collections.tts.modules.discrete_speech_modules.SpeakingRateQuantizer
    num_bins: ${num_speaking_rate}
    min_value: ${fps_min}
    max_value: ${fps_max}

  optim:
    name: adamw
    lr: 4e-5

    sched:
      name: ExponentialLR
      gamma: 0.99

trainer:
  num_nodes: 1
  devices: 1
  accelerator: gpu
  strategy: ddp
  precision: bf16-mixed
  max_epochs: ${max_epochs}
  accumulate_grad_batches: 1
  gradient_clip_val: 5.0
  enable_checkpointing: false # Provided by exp_manager
  logger: false # Provided by exp_manager
  log_every_n_steps: 500
  check_val_every_n_epoch: 1
  benchmark: false
  use_distributed_sampler: false

exp_manager:
  exp_dir: null
  name: ${name}
  create_tensorboard_logger: false
  create_checkpoint_callback: true
  checkpoint_callback_params:
    monitor: val_loss
    always_save_nemo: True
    save_top_k: 3
  resume_if_exists: false
  resume_ignore_no_checkpoint: false
